#!/usr/bin/env lua
require "vmake-edge"

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Configurations
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

Configuration "debug" {
    Data = {
        Opts_CXX = List "-fno-omit-frame-pointer -g3",
    },
}

Configuration "release" {
    Data = {
        Opts_CXX = List "-DNEDEBUG",
    },
}

Configuration "profile" {
    Data = {
        Opts_CXX = List { },
    },

    Base = "release",
}

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Architectures
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

Architecture "any"

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Toolchain
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

GlobalData {
    CXX   = "c++",
    LO    = "c++",
    LD    = "c++",
}

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Tests
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

--  Ditto.

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Dependency Management
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

local settMakeDeps = true

CmdOpt "no-make-deps" {
    Description = "Indicates that GNU Make dependency files are not to be"
             .. "\ngenerated by GCC, G++ or GAS.",

    Handler = function(_, val) settMakeDeps = false end,
}

GlobalData {
    UseMakeDependencies = function()
        return settMakeDeps
    end,
}

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Options and Parameters
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

GlobalData {
    Opts_CXX_Preprocessor = function()
        local res = List {
            "-DVERMILION",
            "-DVERMILION__ARCH=" .. selArch.Name,
            "-DVERMILION__CONF=" .. selConf.Name,
        } --+ Opts_CXX_Tests

        for arch in selArch:Hierarchy() do
            res:Append("-DVERMILION__ARCH_" .. _G.string.upper(arch.Name))
        end

        for conf in selConf:Hierarchy() do
            res:Append("-DVERMILION__CONF_" .. _G.string.upper(conf.Name))
        end

        return res
    end,

    Opts_CXX_Common = function()
        local res = List "-pipe -Wall -Wextra -Wpedantic" + Opts_CXX_Preprocessor + selConf.Data.Opts_CXX

        if settMakeDeps then
            res:Append("-MD"):Append("-MP")
        end

        return res
    end,

    Opts_LLVM_Preprocessor  = DataFromCommand("llvm-config --cppflags"),
    Opts_LLVM_CXX           = DataFromCommand("llvm-config --cxxflags"),
    Opts_LLVM_LD            = DataFromCommand("llvm-config --ldflags"),
    LLVM_Libraries          = DataFromCommand("llvm-config --libs"),
}

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Main File Locations
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

GlobalData {
    CompilerPath = DAT "outDir + 'vermc'",
}

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Projects
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

ManagedProject "Compiler" {
    Languages = { "C++" },
    Target = "Executable",

    Data = {
        BinaryPath = DAT "CompilerPath",
        PrecompiledCppHeader = "common.hpp",

        Opts_CXX = LST "-std=gnu++11 -flto -DVERMILION_COMPILER !Opts_CXX_Common !Opts_Includes !Opts_LLVM_Preprocessor",
        Opts_LD = LST "-fuse-linker-plugin !Opts_CXX !Opts_LLVM_LD",

        Opts_Libraries = function()
            return Libraries:Select(L "|val| '-l' .. val") + LLVM_Libraries
        end,
    },

    Directory = "compiler",

    Output = DAT "CompilerPath",

    CreateMissingDirectoriesRule(true),
}

--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --
--  Wrap up
--  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --  --

Default "Compiler" "any" "debug"

vmake()
